using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TableCodeGen
{
	const string codeTemplate = @"// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class $CLASS : CsvTable
{
	public class Row
	{
$ROW_MEMBER_CODE
	}

	List<Row> rowList = new List<Row>();

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public override void Load(string csvData)
	{
		rowList.Clear();
		string[][] grid = ParserCSV.Parse(csvData);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
$ROW_READ_CODE
			rowList.Add(row);
		}
		isLoaded = true;
	}
    public override string UnLoad()
    {
        for (int i = 1; i < rowList.Count; i++)
        {
            Row row = rowList[i-1];
$ROW_SAVE_CODE
        }
       return UParserCSV.UParser(grid);
    }

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

$FIND_CODE
}";

	const string findCodeTemplate = 
@"	public Row Find_$COLUMN(string find)
	{
		return rowList.Find(x => x.$COLUMN == find);
	}
	public List<Row> FindAll_$COLUMN(string find)
	{
		return rowList.FindAll(x => x.$COLUMN == find);
	}
";

	public static string Generate(string csvText, string className)
	{
		if(string.IsNullOrEmpty(csvText))
			return null;
		
		string[][] grid = ParserCSV.Parse(csvText);
		if(grid.Length < 1)
			return null;

		string rowMemberCode = "";
		string rowReadCode = "";
        string rowSaveCode = "";
		string findCode = "";
		for(int i = 0 ; i < grid[0].Length ; i++)
		{
			rowMemberCode += string.Format("\t\tpublic string {0}{1}\n", grid[0][i], "{get;set;}");
			rowReadCode += string.Format("\t\t\trow.{0} = grid[i][{1}];\n", grid[0][i], i);
            rowSaveCode += string.Format("\t\t\tgrid[i][{0}] = row.{1};\n", i, grid[0][i]);
            findCode += findCodeTemplate.Replace("$COLUMN", grid[0][i]);
        }
		
		string code = codeTemplate;
		code = code.Replace("$CLASS", className);
		code = code.Replace("$ROW_MEMBER_CODE", rowMemberCode);
		code = code.Replace("$ROW_READ_CODE", rowReadCode);
        code = code.Replace("$ROW_SAVE_CODE",rowSaveCode);
		code = code.Replace("$FIND_CODE", findCode);

		return code;
	}
}
