// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class PersonTable : CsvTable
{
    public class Row
    {
        public string name { get; set; }
        public string sex { get; set; }
    }
    List<Row> rowList = new List<Row>();
    public Row this[int index]
    {
        get
        {
            if (rowList.Count > index && index >= 0)
            {
                return rowList[index];
            }
            else
            {
                return null;
            }
        }
    }
    public List<Row> RowList
    {
        get
        {
            return rowList;
        }
    }
    public override void Load(string csvData)
    {
        rowList.Clear();
        grid = ParserCSV.Parse(csvData);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.name = grid[i][0];
            row.sex = grid[i][1];
            rowList.Add(row);
        }
        isLoaded = true;
    }
    public override string UnLoad()
    {
        for (int i = 1; i < rowList.Count; i++)
        {
            Row row = rowList[i - 1];
            grid[i][0] = row.name;
            grid[i][1] = row.sex;

        }
        return UParserCSV.UParser(grid);
    }
}